name: Stellar Ledger Data Indexer

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_protected == 'true' && github.sha || github.ref }}-{{ github.event_name }}
  cancel-in-progress: true

jobs:
  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: Download test ledger data
        run: |
          BASE_URL="https://storage.googleapis.com/sdf-ledger-close-meta/v1/ledgers/pubnet"
          BASE_DIR="/tmp/ledger-test-data"
          PARTITION="FC73CBFF--59520000-59583999"

          mkdir -p "$BASE_DIR/$PARTITION"

          for FILE in \
            "FC7327F5--59561994" \
            "FC7327F4--59561995" \
            "FC7327F3--59561996" \
            "FC7327F2--59561997" \
            "FC7327F1--59561998" \
            "FC7327F0--59561999" \
            "FC7327EF--59562000"
          do
            curl -L --fail --show-error --silent \
              -o "$BASE_DIR/$PARTITION/$FILE.xdr.zstd" \
              "$BASE_URL/$PARTITION/$FILE.xdr.zstd"
          done
        shell: bash

      - name: Run tests
        run: |
          COVERPKGS=$(go list ./... | grep -v '/internal/contract$' | paste -sd ',' -)
          go test -v -coverprofile=${{ runner.workspace }}/coverage.out -coverpkg="$COVERPKGS" ./...

      - name: Check Coverage
        run: |
          COVERAGE=$(go tool cover -func=${{ runner.workspace }}/coverage.out | grep total: | awk '{print $3}' | sed 's/%//')
          echo "Coverage: $COVERAGE%"
          if [ "$(echo "$COVERAGE 80" | awk '{print ($1 < 80)}')" -eq 1 ]; then
            echo "Coverage is below the 80% threshold."
            exit 1
          fi
